#!/bin/bash

PATH=/usr/bin:/bin:/usr/sbin:/sbin:/opt/dns/bin:/opt/dns/sbin

if [ -r /opt/dns/etc/dns-rpz.ip ]; then
    DNS_RPZ_IP=$(grep ^[0-9] /opt/dns/etc/dns-rpz.ip 2> /dev/null | head -1)
fi

if [ "${DNS_RPZ_IP}" == "" ]; then
    DNS_RPZ_IP=192.168.12.18
fi


function rpzCurlList() {
    local url="$1"
    local -i index="$2"

    if [ ${#url} -eq 0 ]; then
        return 1
    fi

    if [ ${#index} -eq 0 ] || [ "${index}" == "0" ]; then
        index=1
    fi

    local domain list_count list_counter list_file list_name

    list_name=$(echo "${url}" | awk -F\/ '{print $3}')
    list_file=/tmp/rpz.block.list.${list_name}

    printf "\n#\n# [${list_name}] ${url}\n#\n\n"
    curl --insecure --location --silent "${url}" | awk "{print \$${index}}" | awk '{print $1}' | grep \\. | egrep -ve '^$|^#|<|>|\[|\]|\/|:' > ${list_file}
    wait $!

    sort -u ${list_file} -o ${list_file}

    list_count=$(cat ${list_file} | wc -l)
    list_counter=0

    while read domain; do
        domain=${domain//_/-}
        domain=${domain//[[:space:]]/}
        let list_counter=${list_counter}+1
        echo "[${list_counter}/${list_count}] [${list_name}] '${domain}'"
        dns add a ${domain}.rpz ${DNS_RPZ_IP} &>> ${list_file}.dns.out
    done < ${list_file}

    rm -f ${list_file} &> /dev/null
    rm -f ${list_file}.dns.out &> /dev/null
}

# i.e. hosts format, second column

Curl_2_Lists=()
Curl_2_Lists=("http://winhelp2002.mvps.org/hosts.txt")

for Curl_2_List in ${Curl_2_Lists[@]}; do
    rpzCurlList "${Curl_2_List}" 2
done

# i.e. first column

Curl_1_Lists=()
Curl_1_Lists+=("http://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblock;showintro=0")
Curl_1_Lists+=("http://mirror2.malwaredomains.com/files/domains.txt")

for Curl_1_List in ${Curl_1_Lists[@]}; do
    rpzCurlList "${Curl_1_List}" 1
done

